[package]
name = "demo"
version = "0.1.0"
authors = ["Alexey Golubev <dr.freecx@gmail.com>"]
edition = "2018"

[dependencies]
statham = { path = "../../statham" }
statham_macro = { path = "../../statham_macro" }